### ISSUE TITLE
Redundancies in data extraction for Archival Items

### ISSUE THREAD

**Issue by tyt3** [CaDatPitt/data-layers#10]
### Issues
- ARCHIVAL_ITEM_MODS_MAP is looking for 'genre', but **serials** have multiple LC subject headings with GenreForm subdivisions. This is also the case for 'namePart'. 
- MODS for serials sometimes have `<typeOfResource>` more than once. 
- Values within `<relatedItem>` tags also cause redundancies. 
- Similar redundancies may also occur in other data elements and in other collections. 

### Solutions
Update code so that it...
- only extracts unique strings, ignoring case. 
- ignore values within `<relatedItem>` tags.

**Comment by mjlavin80** [comment]
I think this is solved. Can someone double check for me once I've rerun the data?

**Comment by tyt3** [comment]
It looks like updates to code are making everything lowercase, which isn't ideal.

**Comment by tyt3** [comment]
Wondering if we can modify code to make the checks for extraction with text lowercased, but to actually retain case for base layer; sometimes case matters for display.
