### ISSUE TITLE
Need Function to Extract "Associated Names"

### ISSUE THREAD

**Issue by tyt3** [CaDatPitt/data-layers#4]
We should extract other names that are associated with the serial. We could search for the name when the roleTerm/@type is not "depositor" and when the name is not a child of copyrightMD:rights.holder.

Rationale:
https://www.loc.gov/standards/mods/v3/mods-userguide-elements.html#name

**Comment by tyt3** [comment]
Leave for extension layer?

**Comment by tyt3** [comment]
This is related to Issue #9 .

**Comment by mjlavin80** [comment]
Find example mods ... maybe serial in American Left Ephemera
