### ISSUE TITLE
Capture dateIssued for Archival Item MODS

### ISSUE THREAD

**Issue by abrennr** [CaDatPitt/data-layers#8]
The current Archival MODS map looks only for `originInfo > dateCreated`. Some items (serials) don't use dateCreated, but instead `originInfo > dateIssued`.

Update code so that `dateCreated` is used for 'date' field when available; if not see if there is a value in `dateIssued` and use it for 'date' field

**Comment by mjlavin80** [comment]
I implemented this fix. Need to re-run data export
