### ISSUE TITLE
Capture additional name varieties for Archival MODS

### ISSUE THREAD

**Issue by abrennr** [CaDatPitt/data-layers#9]
Currently we extract creator names by matching on name anywhere. We then check value of roleTerm to match on 'creator'. This does not capture names that do not have a roleTerm.

These varieties also appear in the source MODS and should be extracted as value of 'creator' field:

` <name type="corporate">
    <namePart>International Union of Mine, Mill, and Smelter Workers</namePart>
  </name>`

` <name type="personal" usage="primary">
    <namePart>Wright, Fred</namePart>
    <namePart type="date">1907-1984</namePart>
  </name>`

**Comment by abrennr** [comment]
suggest changing function to only exclude roleTerm with value of `depositor` and accept everything else in `mods > name > namePart` and not `namePart type='date'` as creator

**Comment by tyt3** [comment]
Should we maintain that value as "creator" or open it up to "associated names"? 

FYI, namePart may also come up in the subject headings converted from the MARC (hence some of the redundancies, see Issue #10 ). I've seen cases where the creator or publisher has come up in the subject headings, but other names may also. That might mean that we need not to include nameParts within the 'subject' tag in the extraction for this data element.

**Comment by mjlavin80** [comment]
I will need additional guidance before I do anything to this. (I previously implemented Aaron's fix.)
